server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
