server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
     routes:
      - id: employee-service
        uri: 1b://EMPLOYEE-SERVICE
        predicates:
          - Path= /employee/**
      - id: department-service
        uri: 1b://DEPARTMENT-SERVICE
          - predicates:
          - Path = /department/**